# Generated by Django 5.0.8 on 2024-08-08 11:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_language'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='question',
            new_name='description',
        ),
        migrations.AddField(
            model_name='quiz',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.RenameModel(
            old_name='QuizOption',
            new_name='PollOption',
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_updated_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('question', models.TextField()),
                ('tip', models.TextField(blank=True, null=True)),
                ('duration', models.IntegerField(default=60)),
                ('quiz', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='polls', to='core.quiz')),
            ],
            options={
                'db_table': 'polls',
            },
        ),
        migrations.AlterField(
            model_name='polloption',
            name='quiz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='options', to='core.poll'),
        ),
    ]
