# Generated by Django 5.0.8 on 2024-08-08 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_quiz_number_of_questions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='polloption',
            old_name='quiz',
            new_name='poll',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='duration',
        ),
        migrations.AddField(
            model_name='quiz',
            name='duration',
            field=models.IntegerField(default=60),
        ),
    ]
