# Generated by Django 5.0.8 on 2024-08-09 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_quiz_polloption_poll_remove_poll_duration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='welcome_message_id',
        ),
    ]
